=== sharjeel-siddiqui12/WST-Lab/Lab8/anthology.dtd
<!ELEMENT anthology (poem1, poem2)>
<!ELEMENT poem1 (title, stanza1, stanza2)>
<!ELEMENT poem2 (title, stanza1)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT stanza1 (line1, line2, line3, line4, line5?, line6?, line7?, line8?)>
<!ELEMENT stanza2 (#PCDATA)>
<!ELEMENT line1 (#PCDATA)>
<!ELEMENT line2 (#PCDATA)>
<!ELEMENT line3 (#PCDATA)>
<!ELEMENT line4 (#PCDATA)>
<!ELEMENT line5 (#PCDATA)>
<!ELEMENT line6 (#PCDATA)>
<!ELEMENT line7 (#PCDATA)>
<!ELEMENT line8 (#PCDATA)>

=== sharjeel-siddiqui12/WST-Lab/Lab8/L8ex2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE anthology SYSTEM "anthology.dtd">
<anthology>
   <poem1>
       <title></title>
       <stanza1>
           <line1></line1>
           <line2></line2>
           <line3></line3>
           <line4></line4>
           <line5></line5>
           <line6></line6>
           <line7></line7>
           <line8></line8>
       </stanza1>
       <stanza2></stanza2>
   </poem1>
   <poem2>
       <title></title>
       <stanza1>
           <line1></line1>
           <line2></line2>
           <line3></line3>
           <line4></line4>
       </stanza1>
   </poem2>
</anthology>
